default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: 10

development:
  <<: *default
  username: 'root'
  password: 'root'
  host: 'localhost'
  socket: '/Applications/MAMP/tmp/mysql/mysql.sock'
  database: tamuhack2019

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: "rails-app"
  password: "tamuhack2019!"
  database: "tamuhack2019"
  socket:   "/cloudsql/tamuhack2019-todo:us-central1:tamuhack2019-todo"

