default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: 10

development:
  <<: *default
  username: 'root'
  password: 'root'
  host: 'localhost'
  socket: '/Applications/MAMP/tmp/mysql/mysql.sock'
  database: tamuhack2019

production:
  <<: *default
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASS'] %>
  socket: <%= ENV['DB_SOCKET'] %>
  database: <%= END['DB_NAME'] %>

